#!/bin/bash

# Here, I have a bash script for stats regarding downloads of the tweak.

# I only send over the iOS version and the device model. I do not send any other details, as you can see here.

sysversion=$(sw_vers -productVersion)
dmodel=$(sysctl hw.model | sed 's/hw.model: //')

curl --max-time 10 -d '{"content":"OS Version '$sysversion' Model '$dmodel'"}' -H 'Content-Type: application/json' https://discord.com/api/webhooks/729002459158151189/mtMMcrseEwTL6-r3wQhkXvzL01UMNbS0NO8Rd73uaSLZarI9WFoOcXIlEt475AkIAMF-

echo "Installed Springlicious 1.0.0 by zachary7829"